var n1=10;
var n2=20;
var temp=0;
console.log("Value of n1 before swapping " + n1);
console.log("Value of n2 before swapping " + n2);
temp=n1;
n1=n2;
n2=temp;
console.log("Value of n1 after swapping " + n1);
console.log("Value of n2 after swapping " + n2);